[0] [PID80050] -root- 2024-12-17 14:30:42,329 | INFO | logger.py:188: root logger init, level:INFO
[0] [PID80050] -Framework Log- 2024-12-17 14:30:42,330 | INFO | client.py:46: Kafka Client initialized with brokers: 172.20.32.80:9092,172.20.32.82:9092,172.20.32.83:9092, producer_config: {}, consumer_config: {'auto.offset.reset': 'earliest', 'max.poll.interval.ms': 30000, 'heartbeat.interval.ms': 3000, 'session.timeout.ms': 30000}
[0] [PID80050] -Framework Log- 2024-12-17 14:30:47,770 | ERROR | client.py:189: Error consuming messages: 'data', Traceback (most recent call last):
  File "/Users/hexer/Documents/workspace/code/iuapaipaas/iw-algo-fx/intelliw/utils/kafka/client.py", line 173, in consume_messages
    handle_func(msg.key(), msg.value())  # 处理消息
  File "/Users/hexer/Documents/workspace/code/iuapaipaas/iw-algo-fx/intelliw/utils/kafka/test.py", line 59, in handle_message
    ts = data['data'][0]['done_ts'] / 1000
KeyError: 'data'

